import asyncio
from playwright.async_api import async_playwright
import re

class AutomationEngine:
    def __init__(self, max_concurrent=5):
        self.max_concurrent = max_concurrent
        self.semaphore = asyncio.Semaphore(self.max_concurrent)
        self.is_cancelled = False

    def cancel(self):
        self.is_cancelled = True

    async def test_single_ip(self, ip, port, username, password, template_script, browser_type="firefox", timeout_ms: int = 15000):
        """ Test a single IP primarily to check if it's reachable and the automation runs. """
        self.is_cancelled = False
        return await self.execute_template_on_router(ip, port, username, password, template_script, visible=True, progress_callback=None, browser_type=browser_type, timeout_ms=timeout_ms)

    async def execute_template_on_router(self, ip, port, username, password, template_script, visible=True, progress_callback=None, browser_type="firefox", timeout_ms: int = 15000):
        if self.is_cancelled:
            if progress_callback:
                progress_callback(ip, "Cancelado")
            return {"ip": ip, "status": "cancelled", "message": "Operação cancelada pelo usuário"}
            
        async with self.semaphore:
            # We wrap the playwright execution inside the semaphore to limit concurrent browsers
            async with async_playwright() as p:
                browser = None
                try:
                    # Depending on the network, headless might be preferred.
                    # Choose browser based on parameter
                    browser_instance = getattr(p, browser_type.lower(), p.firefox)
                    browser = await browser_instance.launch(headless=not visible)
                    context = await browser.new_context(ignore_https_errors=True)
                    page = await context.new_page()
                    # Set page timeout based on user configuration
                    page.set_default_timeout(timeout_ms)
                    
                    if progress_callback:
                        progress_callback(ip, "Iniciando conexão...")
                    
                    # The script stored in DB needs to be executed within this context.
                    # Ideally, the stored script is a python async function body generated by Codegen
                    # Build variables dictionary
                    variables = {
                        "{{IP}}": ip,
                        "{{PORT}}": str(port),
                        "{{USERNAME}}": username,
                        "{{PASSWORD}}": password
                    }
                    
                    # 1. First, replace variables securely
                    for key, val in variables.items():
                        template_script = template_script.replace(key, str(val))
                        
                    # Build local context for exec
                    local_env = {
                        'page': page,
                        'browser': browser,
                        'context': context,
                        'asyncio': asyncio,
                        'variables': variables # Passing variables for possible script usage
                    }
                    
                    script_lines = "\n".join([f"    {line}" for line in template_script.splitlines()])
                    wrapped_script = f"async def run_automation(page):\n{script_lines}"
                    
                    # 2. Add an explicit wait for stability to let router finish processing
                    if progress_callback:
                        progress_callback(ip, "Aplicando configurações...")

                    # Execute the definition into local_env
                    exec(wrapped_script, globals(), local_env)
                    
                    if self.is_cancelled:
                        raise Exception("Operação cancelada pelo usuário")
                    
                    # Run the function
                    # The function is stored in local_env and we must await its execution
                    await local_env['run_automation'](page)
                    
                    if progress_callback:
                        progress_callback(ip, "Sucesso")
                        
                    return {"ip": ip, "status": "success", "message": "Configuração aplicada"}
                
                except Exception as e:
                    if progress_callback:
                        progress_callback(ip, f"Erro: {str(e)}")
                    return {"ip": ip, "status": "error", "message": str(e)}
                finally:
                    if browser:
                        await browser.close()
                    
    def _indent_string(self, text, spaces=4):
        return '\n'.join(' ' * spaces + line if line.strip() else line for line in text.split('\n'))

    async def run_batch(self, devices_list, script, username, password, browser_type="firefox", timeout_ms=15000, progress_callback=None, visible=False):
        """
        devices_list format: [{"ip": "192.168.1.1", "port": "80"}, ...]
        """
        tasks = []
        for dev in devices_list:
            if self.is_cancelled:
                break
                
            # Create a task for each device
            task = self.execute_template_on_router(
                ip=dev['ip'],
                port=dev['port'],
                username=username,
                password=password,
                template_script=script,
                progress_callback=progress_callback,
                visible=visible,
                browser_type=browser_type,
                timeout_ms=timeout_ms
            )
            tasks.append(task)
            
        # Run all tasks concurrently (semaphore limits active ones)
        results = await asyncio.gather(*tasks, return_exceptions=True)
        return results
